apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: fluxcd
spec:
  releaseName: fluxcd
  chart:
    repository: https://charts.fluxcd.io
    version: 1.2.0
    name: flux
  values:
    replicaCount: 1
    git:
      url: 'https://github.com/ahanafy/cluster-base.git'
      branch: 'cleanup'
      pollInterval: '1m'
      readonly: TRUE
      name: 'Fluxcd Operator'
    registry:
      pollInterval: '1m'