apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.4.3/charts
    name: istio
    version: 1.4.3
  values:
    # pilot configuration
    pilot:
      enabled: true
      autoscaleEnabled: true
      sidecar: true
      resources:
        requests:
          cpu: 10m
          memory: 128Mi

    # ingress configuration
    gateways:
      enabled: true
      istio-ingressgateway:
        type: LoadBalancer
        # loadBalancerIP: $IP
        autoscaleEnabled: false
        autoscaleMax: 1
        sds:
          enabled: true

    # sidecar-injector webhook configuration
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: true

    # security configuration
    security:
      enabled: true

    # galley configuration
    galley:
      enabled: true

    # mixer configuration
    mixer:
      policy:
        enabled: false
        replicaCount: 1
        autoscaleEnabled: false
      telemetry:
        enabled: true
        replicaCount: 1
        autoscaleEnabled: false
      resources:
        requests:
          cpu: 10m
          memory: 128Mi

    # addon prometheus configuration
    prometheus:
      enabled: true
      scrapeInterval: 5s

    # addon jaeger tracing configuration
    tracing:
      enabled: true
    
    # addon kiali
    kiali:
      enabled: true
      dashboard: 
        viewOnlyMode: true
        auth:
          strategy: anonymous

    # common settings
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      # sidecar settings
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 2000m
            memory: 256Mi
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: true
      useMCP: true
      # k8sIngress:
      #   enabled: true
      #   enableHttps: true
      #   gatewayName: ingressgateway