apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-init
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio-init
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.4.3/charts
    name: istio-init
    version: 1.4.3
