apiVersion: v1
kind: ConfigMap
metadata:
  name: repositories-values
data:
  repositories.yaml: |-
    configureRepositories:
      enable: true
      volumeName: repositories-yaml
      secretName: flux-helm-repositories
      cacheVolumeName: repositories-cache
      repositories:
        - caFile: ""
          cache: stable-index.yaml
          certFile: ""
          keyFile: ""
          name: stable
          password: ""
          url: https://kubernetes-charts.storage.googleapis.com
          username: ""
        - caFile: ""
          cache: istio.io-index.yaml
          certFile: ""
          keyFile: ""
          name: istio.io
          password: ""
          url: https://storage.googleapis.com/istio-release/releases/1.4.3/charts
          username: ""
        - caFile: ""
          cache: jetstack-index.yaml
          certFile: ""
          keyFile: ""
          name: jetstack
          password: ""
          url: https://charts.jetstack.io
          username: ""          
        - caFile: ""
          cache: flagger-index.yaml
          certFile: ""
          keyFile: ""
          name: flagger
          password: ""
          url: https://flagger.app
          username: ""
