apiVersion: helm.fluxcd.io
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
  values:
    replicaCount: 1
    git:
      url: 'https://github.com/ahanafy/cluster-base.git'
      branch: 'add-helm-release'
      pollInterval: '1m'
      readonly: TRUE
      name: 'Flux Operator'
    registry:
      pollInterval: '1m'