apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io
    version: 1.0.0-rc9
    name: helm-operator
  values:
    chartsSyncInterval: 2m
    git:
      ssh:
        secretName: flux-git-deploy
    helm:
      versions: v3
    configureRepositories:
        enable: true
        volumeName: repositories-yaml
        secretName: flux-helm-repositories
        cacheVolumeName: repositories-cache
        repositories:
            - caFile: ""
              cache: stable-index.yaml
              certFile: ""
              keyFile: ""
              name: stable
              password: ""
              url: https://kubernetes-charts.storage.googleapis.com
              username: ""
            - caFile: ""
              cache: istio.io-index.yaml
              certFile: ""
              keyFile: ""
              name: istio.io
              password: ""
              url: https://storage.googleapis.com/istio-release/releases/1.4.3/charts
              username: ""
            - caFile: ""
              cache: flagger-index.yaml
              certFile: ""
              keyFile: ""
              name: flagger
              password: ""
              url: https://flagger.app
              username: ""