apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    version: v0.13.1
    name: cert-manager
  values:
    replicaCount: 1
    git:
      url: 'https://github.com/ahanafy/cluster-base.git'
      branch: 'master'
      pollInterval: '1m'
      readonly: TRUE
      name: 'Fluxcd Operator'
    registry:
      pollInterval: '1m'