apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: istio-system
spec:
  dnsNames:
    - '*.xip.io'
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer